name: 'Quasar Play Store'
description: 'Connect your GitHub Action workflow to Play Store'
author: 'Anant Negi'
branding:
  icon: 'airplay'
  color: 'gray-dark'

inputs:
  play_store_credentials:
      description: 'Play Store Credentials'
      default: ''
      required: true
  app_version:
      description: 'App Version'
      default: ''
      required: true
    package_name:
      description: 'Package Name'
      default: ''
      required: true
    alias:
      description: 'Secrets Alias'
      default: ''
      required: true
    key_store_password:
      description: 'Secrets Key Store Password'
      default: ''
      required: true
    app_track:
      description: 'App Track'
      default: 'internal'
      required: true
    build_tools_version:
      description: 'Build Tools Version'
      default: '33.0.2'
      required: true
    node_version:
      description: 'Node Version'
      default: '18'
      required: true

env:
  APP_VERSION: ""
  KEYSTORE_BASE64: ""
runs:
    using: 'composite'
    steps:
      - uses: actions/checkout@v3

      - name: Generate Base64 Release Key
        shell: bash
        run: |
          #  | tee signing_keystore_base64_encoded.txt
          # echo "KEYSTORE_BASE64=$(cat signing_keystore_base64_encoded.txt)" >> "$GITHUB_OUTPUT"
          echo "KEYSTORE_BASE64=$(openssl base64 < ${{ inputs.keystore_file }} | tr -d '\n')" >> "$GITHUB_OUTPUT"

      - uses: actions/setup-node@v3
        with:
          node-version: ${{ inputs.node_version }}  # Adjust this to your desired Node.js version

      - name: Append v in APP_VERSION
        shell: bash
        run: |
          echo APP_VERSION="v${{ inputs.app_version }}" >> "$GITHUB_ENV"

      - name: Inputs Print
        shell: bash
        run: |
          echo "Package Name: ${{ inputs.package_name }}"
          echo "App Version: ${{ env.APP_VERSION }}"
          echo "Track: ${{ inputs.app_track }}"
          echo "Bundle Tools Version: ${{ inputs.build_tools_version }}"

