name: Quasar Play Store

on:
  workflow_dispatch:
  push:
    branches:
      - test
  pull_request:
    branches:
      - test

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v3

      - name: Quasar Play Store Action
        uses: ./
        with:
          play_store_credentials: play-store-services.secret
          keystore_file: my-release-key.keystore
          key_store_password: 'XXXXXXXXXX'
          app_version: '1.0.0'
          package_name: 'com.app_name.com'
          alias: 'alias_name'
          app_track: 'internal'
          build_tools_version: '33.0.2'
          node_version: '18'    
